mongo:
  image: mongo:latest
  ports:
   - "27017:27017"
  volumes:
   - './data:/data/db'
application:
  build: .
  command:  bash -c "npm install; nodemon app.js --color=always"
  ports:
   - "9000:9000"
   - "5858:5858"
  volumes:
   - ./app:/usr/src/app
  links:
   - mongo
